import os
import shutil
import datetime
from pathlib import Path
from setuptools import setup
from distutils.dir_util import copy_tree

# Define the names of your main and background scripts
main_script = "GaziGuard.py"
background_script = "background.py"

# Function to run pyinstaller for a given script with options
def run_pyinstaller(script, options):
    command = f"pyinstaller {script} {options}"
    os.system(command)

# Build the main script with icon and without console
run_pyinstaller(main_script, '--icon="icon64.ico" --noconsole --noconfirm')

# Build the background script without console
# run_pyinstaller(background_script, "--noconsole --noconfirm")

# Build the background script with a different destination folder
run_pyinstaller(background_script, "--distpath dist/background_output --noconfirm")

# Get the datetime stamp
datetime_stamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")

#remove last build
merged_output_folder = Path(f"dist/merged_output")
if os.path.exists(merged_output_folder):
    shutil.rmtree(merged_output_folder)

# Merge the contents of the three resulting folders into one single folder
main_dist_folder = Path("dist")
background_dist_folder = Path("dist/background_output")
# merged_output_folder = Path(f"dist/merged_output_{datetime_stamp}")
# merged_output_folder = Path(f"dist/merged_output")
# Copy the main script files
copy_tree(str(main_dist_folder / main_script.split(".")[0]), str(merged_output_folder))

# Copy the background script files
copy_tree(str(background_dist_folder / background_script.split(".")[0]), str(merged_output_folder))

# Remove unnecessary files generated by pyinstaller
for file in merged_output_folder.rglob("__pycache__"):
    shutil.rmtree(file)

# Copy the icon and config.ini files to the merged output folder
shutil.copy("icon64.ico", str(merged_output_folder))


# Create the setup for the merged folder
setup(
    name="GaziGuard",
    version="1.0.2",
    packages=[],
    scripts=[],
)

# Clean up the temporary folders
shutil.rmtree(main_dist_folder)
shutil.rmtree(background_dist_folder)
shutil.rmtree('background.spec')
shutil.rmtree('GaziGuard.spec')

print("Build completed successfully!")
